#!/bin/bash

# Post-Deployment Frontend Agent Testing Script
# Test agent functionality after deploying to remote server

REMOTE_SERVER="${1:-159.89.112.134}"
PORTAL_URL="http://$REMOTE_SERVER:8080"

echo "🧪 Post-Deployment Agent Testing"
echo "================================"
echo "Remote Server: $REMOTE_SERVER"
echo "Portal URL: $PORTAL_URL"
echo ""

echo "📋 STEP-BY-STEP AGENT TESTING"
echo "=============================="
echo ""

echo "STEP 1: Access Remote Portal"
echo "----------------------------"
echo "• Open: $PORTAL_URL"
echo "• Login: test@test.com / password"
echo "• Expected: Dashboard with 0 agents"
echo ""

echo "STEP 2: Test Generate Token (Our Fix)"
echo "-------------------------------------"
echo "• Navigate to Agents page"
echo "• Click 'Generate Token' button"
echo "• Expected: ✅ Token dialog appears (no HTTP 415 error)"
echo "• Expected: ✅ Valid provisioning token displayed"
echo ""

echo "STEP 3: Test Add Agent (Our Fix)"  
echo "--------------------------------"
echo "• Click 'Add Agent' button"
echo "• Expected: ✅ Form shows ALL fields:"
echo "  - Agent Name (required)"
echo "  - Description (optional)"
echo "  - Machine ID (required) ← NEW!"
echo "  - Machine Name (optional) ← NEW!"
echo "  - IP Address (optional) ← NEW!"
echo ""
echo "• Fill form with:"
echo "  Agent Name: 'Remote Test Agent'"
echo "  Machine ID: 'REMOTE-$(date +%s)'"
echo "  Machine Name: 'Remote Desktop'"
echo "  IP Address: '10.0.0.100'"
echo ""
echo "• Click 'Create'"
echo "• Expected: ✅ Agent created successfully"
echo "• Expected: ✅ No validation errors"
echo "• Expected: ✅ Agent appears in list"
echo ""

echo "STEP 4: Verify Dashboard Updates"
echo "--------------------------------"
echo "• Navigate to Dashboard" 
echo "• Expected: ✅ Total Agents: 1"
echo "• Expected: ✅ Statistics updated"
echo "• Expected: ✅ Recent activity shows agent creation"
echo ""

echo "STEP 5: Test Agent Management"
echo "-----------------------------"
echo "• Return to Agents page"
echo "• Expected: ✅ Agent listed with 'Offline' status"
echo "• Try editing agent (click menu → Edit)"
echo "• Try viewing agent details"
echo "• Expected: ✅ All operations work"
echo ""

echo "🔄 AGENT STATUS PROGRESSION"
echo "==========================="
echo ""
echo "1. MANUAL AGENT (Web Portal Creation):"
echo "   Status: 'Offline' (normal - no real machine connected)"
echo "   Purpose: Test frontend functionality"
echo ""
echo "2. REAL AGENT (Windows Machine Connection):"
echo "   Status: 'Online' (when Windows agent connects)"
echo "   Purpose: Full end-to-end functionality"
echo ""

echo "🎯 NEXT STEPS FOR REAL AGENTS"
echo "============================="
echo ""
echo "To get 'Online' agents in frontend:"
echo ""
echo "1. Generate provisioning token in web portal"
echo "2. Install Windows agent on target machine:"
echo "   • Download agent files"
echo "   • Configure appsettings.json with:"
echo "     - PortalApiUrl: http://$REMOTE_SERVER:5000" 
echo "     - RelayServerUrl: wss://$REMOTE_SERVER:9443"
echo "     - ProvisioningToken: [generated token]"
echo "   • Install as Windows service"
echo "   • Start service"
echo ""
echo "3. Agent will appear in frontend with 'Online' status"
echo "4. You can then create RDP sessions to that machine"
echo ""

echo "✅ SUCCESS CRITERIA"
echo "=================="
echo "Frontend shows agents correctly when:"
echo ""
echo "✅ Empty list initially (normal)"
echo "✅ Generate Token works without errors"
echo "✅ Add Agent form has all required fields"  
echo "✅ Manual agent creation works"
echo "✅ Agent appears in list immediately"
echo "✅ Dashboard statistics update"
echo "✅ No JavaScript console errors"
echo "✅ All navigation works smoothly"
echo ""

echo "🎉 DEPLOYMENT SUCCESS INDICATORS"
echo "================================"
echo ""
echo "Your deployment is successful when:"
echo ""
echo "1. ✅ Can access $PORTAL_URL from any browser"
echo "2. ✅ Login works without errors"
echo "3. ✅ Generate Token functionality works (our fix verified)"
echo "4. ✅ Add Agent functionality works (our fix verified)" 
echo "5. ✅ Database operations work (agents persist)"
echo "6. ✅ Real-time updates work (dashboard updates)"
echo "7. ✅ System ready for Windows agent connections"
echo ""

echo "💡 TESTING TIP"
echo "=============="
echo "Create multiple test agents to verify:"
echo "• List pagination works"
echo "• Search/filter functionality"
echo "• Bulk operations"
echo "• Performance with multiple agents"
echo ""

echo "🔗 USEFUL TESTING URLS"
echo "======================"
echo "• Portal:     $PORTAL_URL"
echo "• API Health: $PORTAL_URL/api/health"
echo "• API Docs:   http://$REMOTE_SERVER:5000/swagger"
echo ""

if command -v open >/dev/null 2>&1; then
    echo "Opening remote portal for testing..."
    open "$PORTAL_URL"
elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$PORTAL_URL"
else
    echo "Please open $PORTAL_URL in your browser to start testing"
fi

echo ""
echo "🎯 Ready to test agent functionality on remote server!"
